//NAVIGATION
export const GO_LOGIN = "GO_LOGIN";
export const GO_MAINCASHIER = "GO_MAINCASHIER";
export const GO_STATUSMESA = "GO_STATUSMESA";
export const GO_MAINCHARGE = "GO_MAINCHARGE";
export const GO_ACTUALCASHIER = "GO_ACTUALCASHIER";
export const GO_CASHIERRESUME = "GO_CASHIERRESUME";
export const GO_CASHIERREGISTER = "GO_CASHIERREGISTER";
export const GO_ORDERDETAILS = "GO_ORDERDETAILS";
//GUI
export const TURN_SHADOW_CARD_OFF = "TURN_SHADOW_CARD_OFF";
//HTTP REQUESTS
export const SEND_ORDER = "SEND_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const SET_PAX = "SET_PAX";
export const GET_COMANDA = "GET_COMANDA";
export const GET_CATALOG = "GET_CATALOG";
export const CLEAR_CATALOG = "CLEAR_CATALOG";
//PASS DATA
export const SEND_ITEM = "SEND_ITEM";
//TOP BAR CONFIG
export const SAVE_CLIENT_ZOHO = "SAVE_CLIENT_ZOHO";
export const SET_FONDO_ID = "SET_FONDO_ID";
export const SET_CAJERO_ID = "SET_CAJERO_ID";
export const SET_CARGO = "SET_CARGO";
export const SAVE_TOKEN = "SAVE_TOKEN";
export const SET_FIRST_TITLE = "SET_FIRST_TITLE";
export const SET_SECOND_TITLE = "SET_SECOND_TITLE";
export const SET_THIRD_TITLE = "SET_THIRD_TITLE";
export const SET_FOURTH_TITLE = "SET_FOURTH_TITLE";
export const SET_FIRST_DATA = "SET_FIRST_DATA";
export const SET_SECOND_DATA = "SET_SECOND_DATA";
export const SET_THIRD_DATA = "SET_THIRD_DATA";
export const SET_FOURTH_DATA = "SET_FOURTH_DATA";
export const SET_FIRST_TOP = "SET_FIRST_TOP";
export const SET_SECOND_TOP = "SET_SECOND_TOP";
export const SET_FIRST_BOTTOM = "SET_FIRST_BOTTOM";
export const SET_SECOND_BOTTOM = "SET_SECOND_BOTTOM";
export const SET_TEXT_ALIGN_FIRST_BOTTOM = "SET_TEXT_ALIGN_FIRST_BOTTOM";
export const SET_FONT_SIZE_SECOND_BOTTOM = "SET_FONT_SIZE_SECOND_BOTTOM";
export const SET_FONT_WEIGHT_SECOND_BOTTOM = "SET_FONT_WEIGHT_SECOND_BOTTOM";
export const SET_TOP_BAR_VISIBILITY = "SET_TOP_BAR_VISIBILITY";
//GET AND UPDATE MESAS
export const SET_MESA_ESTADO = "SET_MESA_ESTADO";
export const GET_MESAS = "GET_MESAS";
export const SET_TABLE_NUMBER = "SET_TABLE_NUMBER";
export const GET_MESA_ID = "GET_MESA_ID";
//SET CHECK
export const SET_ORDER = "SET_ORDER";
//PASS ITEM TO CHECK/LIST
export const PASS_ITEM_TO_CHECK = "PASS_ITEM_TO_CHECK";
export const PASS_ITEM_TO_LIST = "PASS_ITEM_TO_LIST";
export const SET_INDEX_CHECK = "SET_INDEX_CHECK";
export const SET_INDEX_SUBCHECK = "SET_INDEX_SUBCHECK";
//PASS ITEM TO FINAL CHECK
export const FILL_CHECKS = "FILL_CHECKS";
//GET RECARGO SETTING
export const GET_RECARGOS = "GET_RECARGOS"
